# Generated by Django 3.2.14 on 2022-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoori_recipes', '0002_auto_20220722_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
