# Generated by Django 3.2.14 on 2022-07-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoori_recipes', '0003_auto_20220727_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(null=True),
        ),
    ]
